### ISSUE TITLE
gwt-maven-plugin and multiple module

### ISSUE THREAD

**Issue by castrogne** [mojohaus/gwt-maven-plugin#2]
Hi,

I would like to know if it's possible to have 2 modules in the same project. If my project has 2 html end 2 entries in GXT, how may i use the plugin? Sorry, didn't found answer anywhere...

Should i : 

```
  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <version>${gwt.version}</version>
    <configuration>
      ....
      <module>mypackage.module1</module>
      <module>mypackage.module2</module>
    </configuration>
    ...
  </plugin>
```

or : 

```
  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <version>${gwt.version}</version>
    <configuration>
      ....
      <module>mypackage.module1</module>
    </configuration>
    ...
  </plugin>
  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <version>${gwt.version}</version>
    <configuration>
      ....
      <module>mypackage.module2</module>
    </configuration>
    ...
  </plugin>
```

Many thanks,

**Comment by ibaca** [comment]
First one, but nested inside a modules tag.

```
<modules>
  <module>...</module>
  <module>...</module>
</modules>
```

But the plugin automatically finds all your gwt.xml modules if you do not define any module at all.
https://gwt-maven-plugin.github.io/gwt-maven-plugin/user-guide/compile.html#Configure_GWT_modules

**Comment by olamy** [comment]
this project is now maintained by @tbroyer and not hosted here

**Comment by tbroyer** [comment]
@olamy FYI, I'm actually in the process of resigning. I have https://tbroyer.github.io/gwt-maven-plugin now.

**Comment by castrogne** [comment]
Many thanks for all your answers.

Regards,

**Comment by batmat** [comment]
@tbroyer I think this means we should deprecate the current repository. I can't see how anybody could support GWT (-maven-plugin) better than you.

**Comment by tbroyer** [comment]
Here's the current status: we currently have
- https://github.com/gwt-maven-plugin/gwt-maven-plugin, the historical post-svn repo for Mojo's plugin, initially created by ndeloof I believe. @ibaca has been helping lately, others had expressed intents.
- this repo: migrated from the legacy (and out of date) CodeHaus svn.
- my new from-scratch plugin

Mojo's plugin still has to decide what to do with its two repos: move to mojohaus or keep the current one; and close the other anyway. As I said many times, I for one don't care, as I no longer care about Mojo's plugin. 

Mojo's plugin has too many design mistakes IMO (I don't blame anyone) and technical debt, which is why I started from scratch. I'm hoping to reach 1.0 before the next GWT release, so I continue to support GWT in the Maven world.

The "community" will have to decide what to do with Mojo's plugin. Maintenance of the plugin is quite straightforward if all you do is update it for new GWT releases and fix bugs, anybody could do it and I'll help for the first release; so it could very well live after me.

**Comment by ibaca** [comment]
I added a topic https://groups.google.com/forum/#!forum/codehaus-mojo-gwt-maven-plugin-users to delete the mojohaus repo, I'm no one to take that decision :relaxed:, but with this strategy it's easier to get conclusion because if no one commented in the next weeks, I suppose that the community is ok to the decision of deleting this repo.

I will continue helping until the mojohaus migration end up (currently deploy and even compilation has some problems). And I'll try to continue after that.
